kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource
subjects:
- kind: ServiceAccount
  name: resource
roleRef:
  kind: Role
  name: resource
  apiGroup: rbac.authorization.k8s.io